# Prometheus configuration for TaylorDash
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TaylorDash backend API
  - job_name: 'taylordash-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # VictoriaMetrics
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
    metrics_path: '/metrics'

  # Node exporter (if added later)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # MQTT exporter (if added later)
  # - job_name: 'mqtt'
  #   static_configs:
  #     - targets: ['mqtt-exporter:9090']